import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/ui/header";
import { Roboto } from "next/font/google";
import TopLoader from "./components/ui/topLoader";
import { AuthProvider } from "./contexts/AuthContext";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pica Pau",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className={`${roboto.className} -z-50 bg-gradient-to-t from-[#191a27aa] to-black/10]`}
          id="shadow-box"
          style={{ backgroundColor: "#0d1b3150" }}
        >
          <AuthProvider>
            <Header />
            <TopLoader />
            {children}
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
