import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/header";
import { Roboto } from "next/font/google";
import { HeaderProvider } from "./contexts/HeaderContext";
import { AdminProvider } from "./contexts/AdminContext";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pica Pau",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          className={`${roboto.className}`}
          id="shadow-box"
          style={{ backgroundColor: "#0d1b3150" }}
        >
          <AdminProvider>
            <HeaderProvider>
              <Header />
              {children}
            </HeaderProvider>
          </AdminProvider>
        </div>
      </body>
    </html>
  );
}
